name: CI

on:
  push:
    branches:
      - main
      - 'release/*'
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Compile Project
      run: |
        ./mvnw compile
        
    - name: Run Unit Tests
      run: |
        ./mvnw test
        
    - name: Generate Javadoc
      run: |
        ./mvnw javadoc:javadoc
        
    - name: Upload Javadoc
      uses: actions/upload-artifact@v2
      with:
        name: javadoc
        path: target/site/apidocs

    - name: Report Results
      run: echo "CI Pipeline completed successfully."

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
